/* awob client C ABI — generated by cbindgen, do not edit. */

#ifndef AWOB_CLIENT_H
#define AWOB_CLIENT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#define awob_AWOB_OK 0

#define awob_AWOB_ERR_BAD_ARG 1

#define awob_AWOB_ERR_CONNECT 2

#define awob_AWOB_ERR_IO 3

#define awob_AWOB_ERR_PROTOCOL 4

#define awob_AWOB_ERR_DAEMON 5



#define awob_AWOB_ABI_VERSION 0

#endif  /* AWOB_CLIENT_H */
